import { addColumnIfMissing, type Migration } from "../schema";

/** `ALTER TABLE` fragments for every column added after `config` first shipped. */
export const CONFIG_MIGRATIONS = [
  `system_prompt TEXT NOT NULL DEFAULT ''`,
  `agent_name TEXT NOT NULL DEFAULT ''`,
  `temperature REAL NOT NULL DEFAULT 0.7`,
  `max_tokens INTEGER NOT NULL DEFAULT 0`,
  `reasoning_effort TEXT NOT NULL DEFAULT 'off'`,
  `context_messages INTEGER NOT NULL DEFAULT 0`,
  `cap_web_search INTEGER NOT NULL DEFAULT 0`,
  `cap_url_fetch INTEGER NOT NULL DEFAULT 0`,
  `cap_file_ingest INTEGER NOT NULL DEFAULT 0`,
  `cap_vision INTEGER NOT NULL DEFAULT 0`,
  `cap_image_generation INTEGER NOT NULL DEFAULT 0`,
  `cap_audio_input INTEGER NOT NULL DEFAULT 0`,
  `cap_scheduled_tasks INTEGER NOT NULL DEFAULT 0`,
  `cap_memory INTEGER NOT NULL DEFAULT 0`,
  `cap_telegram INTEGER NOT NULL DEFAULT 0`,
  `brave_api_key TEXT NOT NULL DEFAULT ''`,
  // Backfill for rows that predate the column, frozen at what the column shipped with.
  // A row written since always carries the deployment's `config_defaults`.
  `image_model TEXT NOT NULL DEFAULT 'google/gemini-2.5-flash-image'`,
  `transcription_model TEXT NOT NULL DEFAULT 'google/gemini-2.5-flash-lite'`,
  `telegram_bot_token TEXT NOT NULL DEFAULT ''`,
  `telegram_bot_username TEXT NOT NULL DEFAULT ''`,
  `telegram_user_whitelist TEXT NOT NULL DEFAULT ''`,
  `telegram_group_whitelist TEXT NOT NULL DEFAULT ''`,
  `cap_mcp INTEGER NOT NULL DEFAULT 1`,
  `searxng_url TEXT NOT NULL DEFAULT ''`,
  `searxng_token TEXT NOT NULL DEFAULT ''`,
  `openrouter_api_key TEXT NOT NULL DEFAULT ''`,
];

/**
 * The `config` columns WhatsApp added, as `ALTER TABLE` fragments.
 *
 * A rung of their own rather than more entries in `CONFIG_MIGRATIONS`, because that
 * list is only ever run by the baseline step — and the baseline runs once per object,
 * before the ladder existed or on the object's first touch. An object that already
 * passed it never sees an entry appended to the list, so it goes on without the
 * column until the first statement that names one fails: `no such column:
 * cap_whatsapp`, from every read of the settings, including the one that deletes the
 * agent. Columns added from here on go in a new step below, never in that list.
 */
export const WHATSAPP_CONFIG_COLUMNS = [
  `cap_whatsapp INTEGER NOT NULL DEFAULT 0`,
  `whatsapp_phone_number_id TEXT NOT NULL DEFAULT ''`,
  `whatsapp_access_token TEXT NOT NULL DEFAULT ''`,
  `whatsapp_app_secret TEXT NOT NULL DEFAULT ''`,
  `whatsapp_verify_token TEXT NOT NULL DEFAULT ''`,
  `whatsapp_number TEXT NOT NULL DEFAULT ''`,
];

/**
 * One agent's tables, in the order they were introduced.
 *
 * Step 0 is the baseline — everything that existed before this ladder did, written
 * idempotently because every live agent already has it. Append below; do not edit it.
 */
export const SESSION_REGISTRY_MIGRATIONS: readonly Migration[] = [
  {
    name: "baseline",
    up: (sql) => {
      sql.exec(
        `CREATE TABLE IF NOT EXISTS sessions (
           id TEXT PRIMARY KEY,
           title TEXT NOT NULL,
           created_at INTEGER NOT NULL,
           updated_at INTEGER NOT NULL,
           object_id TEXT NOT NULL DEFAULT '',
           source TEXT NOT NULL DEFAULT 'web',
           chat_id TEXT NOT NULL DEFAULT '',
           chat_type TEXT NOT NULL DEFAULT '',
           chat_username TEXT NOT NULL DEFAULT '',
           chat_thread_id TEXT NOT NULL DEFAULT ''
         )`
      );
      for (const col of [
        `object_id TEXT NOT NULL DEFAULT ''`,
        `source TEXT NOT NULL DEFAULT 'web'`,
        `chat_id TEXT NOT NULL DEFAULT ''`,
        `chat_type TEXT NOT NULL DEFAULT ''`,
        `chat_username TEXT NOT NULL DEFAULT ''`,
        `chat_thread_id TEXT NOT NULL DEFAULT ''`,
      ])
        addColumnIfMissing(sql, "sessions", col);
      sql.exec(
        `CREATE TABLE IF NOT EXISTS config (
           id INTEGER PRIMARY KEY CHECK (id = 1),
           model TEXT NOT NULL
         )`
      );
      // Bring forward config rows created before the tuning and capability columns.
      for (const col of CONFIG_MIGRATIONS) addColumnIfMissing(sql, "config", col);
      sql.exec(
        `CREATE TABLE IF NOT EXISTS meta (
           id INTEGER PRIMARY KEY CHECK (id = 1),
           json TEXT NOT NULL DEFAULT ''
         )`
      );
      // What the agent's turns have cost, one row per calendar month, in US dollars.
      //
      // A running total rather than a sum over the sessions: usage rows live in each
      // session's own object, so answering "what has this agent spent this month"
      // from them would mean opening every session the agent has ever had, on every
      // turn. The sessions report what they spend here instead, which makes the
      // question one read of one row.
      // Uploaded and generated bytes, agent-wide. One row, moved by each session as it
      // writes and deletes files. See `max_agent_bytes` in settings.ts.
      sql.exec(
        `CREATE TABLE IF NOT EXISTS storage (
           id INTEGER PRIMARY KEY CHECK (id = 1),
           bytes INTEGER NOT NULL DEFAULT 0
         )`
      );

      sql.exec(
        `CREATE TABLE IF NOT EXISTS spend (
           month TEXT PRIMARY KEY,
           usd REAL NOT NULL DEFAULT 0
         )`
      );
      // Who may open this agent, and who administers it. Deliberately its own table
      // and not a pair of columns on `config`: that row is walked by `redact` and
      // `validateConfig` in the Worker, returned whole by `GET /config` and patched by
      // `PATCH /config` — so an access column living there would be both readable by
      // the browser and editable by anyone the list already lets in. The gate may not
      // be reachable from the thing it guards.
      sql.exec(
        `CREATE TABLE IF NOT EXISTS access (
           id INTEGER PRIMARY KEY CHECK (id = 1),
           allowed_emails TEXT NOT NULL DEFAULT '',
           admin_email TEXT NOT NULL DEFAULT '',
           seeded INTEGER NOT NULL DEFAULT 0
         )`
      );
      sql.exec(
        `CREATE TABLE IF NOT EXISTS memories (
           id INTEGER PRIMARY KEY AUTOINCREMENT,
           text TEXT NOT NULL,
           session_id TEXT NOT NULL,
           created_at INTEGER NOT NULL
         )`
      );
      sql.exec(
        `CREATE TABLE IF NOT EXISTS mcp_servers (
           id TEXT PRIMARY KEY,
           name TEXT NOT NULL,
           url TEXT NOT NULL,
           auth TEXT NOT NULL DEFAULT 'none',
           headers TEXT NOT NULL DEFAULT '',
           enabled INTEGER NOT NULL DEFAULT 1,
           oauth_client_id TEXT NOT NULL DEFAULT '',
           oauth_client_secret TEXT NOT NULL DEFAULT '',
           oauth_access_token TEXT NOT NULL DEFAULT '',
           oauth_refresh_token TEXT NOT NULL DEFAULT '',
           oauth_expires_at INTEGER NOT NULL DEFAULT 0,
           oauth_scope TEXT NOT NULL DEFAULT '',
           oauth_token_url TEXT NOT NULL DEFAULT '',
           oauth_authorize_url TEXT NOT NULL DEFAULT '',
           oauth_registration_url TEXT NOT NULL DEFAULT '',
           oauth_resource TEXT NOT NULL DEFAULT '',
           oauth_verifier TEXT NOT NULL DEFAULT '',
           oauth_state TEXT NOT NULL DEFAULT '',
           oauth_return_to TEXT NOT NULL DEFAULT '',
           tools_json TEXT NOT NULL DEFAULT '',
           disabled_tools TEXT NOT NULL DEFAULT '',
           tools_synced_at INTEGER NOT NULL DEFAULT 0,
           last_error TEXT NOT NULL DEFAULT '',
           created_at INTEGER NOT NULL DEFAULT 0
         )`
      );
      // Bring forward server rows created before a column was added.
      for (const col of [`disabled_tools TEXT NOT NULL DEFAULT ''`])
        addColumnIfMissing(sql, "mcp_servers", col);
    },
  },
  {
    name: "whatsapp delivery dedupe",
    up: (sql) => {
      // Meta re-delivers a webhook until it gets a fast 200, and a slow turn is
      // exactly what produces a retry — so the same `wamid` arrives two or three
      // times and, without this, is answered two or three times.
      //
      // It lives in the registry rather than in the session because the check has to
      // happen at the webhook, before a session has been resolved or created: two
      // concurrent deliveries of a first message would otherwise race to create two
      // sessions for one conversation.
      sql.exec(
        `CREATE TABLE IF NOT EXISTS whatsapp_events (
           id TEXT PRIMARY KEY,
           seen_at INTEGER NOT NULL
         )`
      );
    },
  },
  {
    name: "whatsapp config columns",
    up: (sql) => {
      // `addColumnIfMissing` rather than a bare `ALTER`, which a step after the
      // baseline would normally use: the deploy that first shipped WhatsApp added
      // these columns to `CONFIG_MIGRATIONS`, so every object created while that code
      // was live already has them and would fail this rung on a duplicate column.
      for (const col of WHATSAPP_CONFIG_COLUMNS) addColumnIfMissing(sql, "config", col);
    },
  },
  {
    name: "whatsapp waba id",
    up: (sql) => {
      // The account id the app has to be subscribed to. Added after the columns
      // above, so agents configured before it have it blank and are asked for it the
      // next time their settings are opened.
      addColumnIfMissing(sql, "config", `whatsapp_waba_id TEXT NOT NULL DEFAULT ''`);
    },
  },
  {
    name: "voice note columns",
    up: (sql) => {
      // What the agent speaks with, and whether it may. Agents that predate this have
      // the capability off and the model at its default, which is the same state a
      // new agent arrives in.
      addColumnIfMissing(sql, "config", `cap_voice_output INTEGER NOT NULL DEFAULT 0`);
      addColumnIfMissing(
        sql,
        "config",
        `voice_model TEXT NOT NULL DEFAULT 'openai/gpt-audio-mini'`
      );
    },
  },
  {
    name: "guests, session owners and notes",
    up: (sql) => {
      addColumnIfMissing(sql, "access", `guests INTEGER NOT NULL DEFAULT 0`);
      addColumnIfMissing(sql, "access", `guest_emails TEXT NOT NULL DEFAULT ''`);
      addColumnIfMissing(sql, "sessions", `owner_email TEXT NOT NULL DEFAULT ''`);
      sql.exec(`CREATE INDEX IF NOT EXISTS idx_sessions_owner ON sessions(owner_email)`);
      addColumnIfMissing(sql, "config", `private_notes TEXT NOT NULL DEFAULT ''`);
      addColumnIfMissing(sql, "config", `public_notes TEXT NOT NULL DEFAULT ''`);
    },
  },
];
