import type { Config, Memory, SessionRegistry } from "./registry";
import type { DeploymentSettings } from "./settings";
import {
  McpClient,
  McpUnauthorized,
  parseHeaders,
  parseNames,
  parseTools,
  qualifiedName,
  type McpServerRow,
} from "./mcp";
import { VOICE_SAMPLE_RATE, pcm16ToOggOpus } from "./opus";

/**
 * Something the agent can do beyond writing. Tool capabilities give the model functions;
 * input capabilities change what a turn may carry (files, images, audio). Sent to the UI as-is.
 */
export type CapabilityId =
  | "web_search"
  | "url_fetch"
  | "file_ingest"
  | "vision"
  | "image_generation"
  | "audio_input"
  | "voice_output"
  | "scheduled_tasks"
  | "memory"
  | "telegram"
  | "whatsapp"
  | "mcp";

/** A credential or endpoint the user fills in on the capabilities page. */
export type CapabilityField = {
  key: keyof Config;
  label: string;
  hint?: string;
  /** Secrets are write-only over the API: reads return a mask, not the value. */
  secret: boolean;
  /**
   * A fixed choice rather than free text, since most OpenRouter ids would not work. Empty
   * here: `capabilitiesFor` fills it from the deployment's `field_options`.
   */
  options?: { value: string; label: string }[];
  /**
   * The field holds a list, one entry per line, edited as a set of chips rather than
   * as free text.
   */
  list?: boolean;
  /** A capability with an empty required field is enabled but cannot run. */
  required: boolean;
  placeholder?: string;
};

export type Capability = {
  id: CapabilityId;
  /**
   * The capability is always on and has no switch. Its own configuration decides
   * whether it does anything — MCP does nothing until a server is connected.
   */
  alwaysOn?: boolean;
  /** The config column that switches it on. */
  flag: keyof Config;
  /**
   * Where the conversation arrived from, not an action: no tools, and replies go back on
   * the same channel. Listed as a capability, the model offered to message arbitrary numbers.
   */
  channel?: true;
  label: string;
  summary: string;
  /** What it costs or risks, shown under the toggle. */
  note?: string;
  /** Setup guide for this capability's credentials, opened in a new tab. */
  guide?: { label: string; href: string };
  tools: string[];
  fields: CapabilityField[];
};

/**
 * Whitelist placeholders that match nothing, seeded on first enable: an empty list
 * would open the bot to all of Telegram.
 */
export const TELEGRAM_WHITELIST_DEFAULTS = {
  telegram_user_whitelist: "@no-user",
  telegram_group_whitelist: "-1000000000000",
} as const;

export const CAPABILITIES: Capability[] = [
  {
    id: "web_search",
    flag: "cap_web_search",
    label: "Web search",
    summary: "Get answers from the live web, with links.",
    tools: ["web_search"],
    fields: [
      {
        key: "brave_api_key",
        label: "Brave Search API key",
        secret: true,
        required: false,
        placeholder: "BSA…",
      },
      {
        key: "searxng_url",
        label: "SearXNG URL",
        hint: "Self-hosted web search fallback, used when no Brave API key is set. You can run it locally or host it on a server yourself. (Agent will need a publicly accessible URL; use a tunnel like cloudflared).",
        secret: false,
        required: false,
        placeholder: "https://local-searxng-project.trycloudflare.com",
      },
      {
        key: "searxng_token",
        label: "SearXNG token",
        hint: "API token generated by SearXNG on first run.",
        secret: true,
        required: false,
        placeholder: "",
      },
    ],
  },
  {
    id: "url_fetch",
    flag: "cap_url_fetch",
    label: "Read a URL",
    summary: "Open a link you share and read the page.",
    tools: ["fetch_url"],
    fields: [],
  },
  {
    id: "file_ingest",
    flag: "cap_file_ingest",
    label: "File ingest",
    summary: "Ask questions about files you attach.",
    note: "Markdown, CSV, JSON and code up to 1 MB; PDFs up to 8 MB.",
    tools: [],
    fields: [],
  },
  {
    id: "vision",
    flag: "cap_vision",
    label: "Image input",
    summary: "Ask questions about images you attach.",
    note: "Not available for all models.",
    tools: [],
    fields: [],
  },
  {
    id: "image_generation",
    flag: "cap_image_generation",
    label: "Image generation",
    summary: "Agent will be able to generate images when requested.",
    tools: ["generate_image"],
    fields: [
      {
        key: "image_model",
        label: "Image model",
        secret: false,
        required: true,
        // Filled from the deployment's `field_options`: the code ships no menu.
        options: [],
      },
    ],
  },
  {
    id: "audio_input",
    flag: "cap_audio_input",
    label: "Audio input",
    summary: "Agent will be able to listen to voice notes and audio files.",
    tools: ["transcribe_audio"],
    fields: [
      {
        key: "transcription_model",
        label: "Transcription model",
        secret: false,
        required: true,
        // Filled from the deployment's `field_options`: the code ships no menu.
        options: [],
      },
    ],
  },
  {
    id: "voice_output",
    flag: "cap_voice_output",
    label: "Voice notes",
    summary: "Agent will be able to answer with a voice note on WhatsApp and Telegram.",
    note: "Chat channels only. The reply is still sent as text; the note goes with it.",
    tools: ["send_voice_note"],
    fields: [
      {
        key: "voice_model",
        label: "Voice model",
        secret: false,
        required: true,
        // Filled from the deployment's `field_options`: the code ships no menu.
        options: [],
      },
    ],
  },
  {
    id: "scheduled_tasks",
    flag: "cap_scheduled_tasks",
    label: "Schedule tasks",
    summary: "Allow the agent to run a task at a specified time or on a recurring schedule.",
    tools: ["schedule_task", "list_scheduled_tasks", "cancel_scheduled_task"],
    fields: [],
  },
  {
    id: "telegram",
    flag: "cap_telegram",
    channel: true,
    label: "Telegram",
    summary: "Talk to the agent on Telegram, in a DM or in a group.",
    tools: [],
    fields: [
      {
        key: "telegram_bot_token",
        label: "Bot token",
        hint: 'Get a bot token by sending this message "/newbot" to @BotFather in Telegram.',
        secret: true,
        required: true,
        placeholder: "123456:ABC…",
      },
      {
        key: "telegram_bot_username",
        label: "Bot username",
        hint: "A Telegram bot username will begin with an @ and ends with bot",
        secret: false,
        required: true,
        placeholder: "@my_agent_bot",
      },
      {
        key: "telegram_user_whitelist",
        label: "DM whitelist",
        hint: "Usernames allowed to DM the bot. Empty list allows every user. (Wrap an entry in slashes for a regex, e.g. /^team_/)",
        secret: false,
        list: true,
        required: false,
        placeholder: "@alice",
      },
      {
        key: "telegram_group_whitelist",
        label: "Groups whitelist",
        hint: "Groups and Topics the bot can reply in. Enter group_id or group_id:topic_id (regex supported). Empty list allows every group and forum. (You can find group id and topic id by messaging @userinfobot)",
        secret: false,
        list: true,
        required: false,
        placeholder: "-1001234567890 or -1001234567890:42",
      },
    ],
  },
  {
    id: "whatsapp",
    flag: "cap_whatsapp",
    channel: true,
    label: "WhatsApp",
    summary: "Talk to the agent on WhatsApp. Follow the setup guide below.",
    note: "Meta will only provide one additional test phone number per user pending business verification",
    guide: { label: "WhatsApp setup guide", href: "/guides/whatsapp" },
    tools: [],
    fields: [
      {
        key: "whatsapp_number",
        label: "Your WhatsApp number",
        hint: "Enter your full number including the country code without any spaces or symbols except digits.",
        secret: false,
        required: true,
        placeholder: "919876543210",
      },
      {
        key: "whatsapp_phone_number_id",
        label: "Phone number ID",
        secret: false,
        required: true,
        placeholder: "123456789012345",
      },
      {
        key: "whatsapp_waba_id",
        label: "WhatsApp Business account ID",
        secret: false,
        required: true,
        placeholder: "123456789012345",
      },
      {
        key: "whatsapp_access_token",
        label: "Access token",
        secret: true,
        required: true,
        placeholder: "EAA…",
      },
      {
        key: "whatsapp_app_secret",
        label: "App secret",
        secret: true,
        required: true,
        placeholder: "32 hex characters",
      },
      {
        key: "whatsapp_verify_token",
        label: "Verify token",
        secret: false,
        required: true,
        placeholder: "a phrase only you know",
      },
    ],
  },
  {
    id: "mcp",
    flag: "cap_mcp",
    alwaysOn: true,
    label: "MCP servers",
    summary:
      "Connect to any external MCP server or select an MCP server template from the list below.",
    // The servers are rows, not settings, so this capability's editor is its own
    // component rather than a list of fields.
    tools: [],
    fields: [],
  },
  {
    id: "memory",
    flag: "cap_memory",
    label: "Private Memory",
    summary:
      "Let the agent remember facts from conversations. These facts are not shared with other agents.",
    tools: ["remember", "recall"],
    fields: [],
  },
];

/** What a secret reads back as, so a key shows as set without being handed out. */
export const SECRET_MASK = "••••••••";

export const CAPABILITY_BY_ID = new Map(CAPABILITIES.map((c) => [c.id, c]));

/** Whether a capability is switched on *and* has everything it needs to run. */
export function capabilityReady(capability: Capability, config: Config): boolean {
  // A capability with no switch is on regardless of what an older config row says.
  if (!capability.alwaysOn && !config[capability.flag]) return false;
  return capability.fields.every((f) => !f.required || String(config[f.key] ?? "").trim() !== "");
}

/** The ready capabilities to name to the model. Channels are excluded: they are not abilities. */
export function capabilityLabels(config: Config): string[] {
  return CAPABILITIES.filter((c) => !c.channel && capabilityReady(c, config)).map((c) => c.label);
}

/** Where the agent can be reached, which is a different claim from what it can do. */
export function channelLabels(config: Config): string[] {
  return CAPABILITIES.filter((c) => c.channel && capabilityReady(c, config)).map((c) => c.label);
}

export function enabled(config: Config, id: CapabilityId): boolean {
  const capability = CAPABILITY_BY_ID.get(id);
  return capability ? capabilityReady(capability, config) : false;
}

/* ------------------------------------------------------------------ tools -- */

export type ScheduledTask = { id: string; prompt: string; when: string };

/**
 * What a tool may touch. Tools are pure functions of their arguments plus this, which
 * keeps them testable and the Durable Object's internals out of them.
 */
export type ToolContext = {
  config: Config;
  /** The deployment's ceilings, for the tools that enforce one. */
  settings: DeploymentSettings;
  sessionId: string;
  /** The Worker's OpenRouter key, for tools that call a model of their own. */
  openrouterKey: string;
  registry: DurableObjectStub<SessionRegistry>;
  /** Stores an image and returns a URL this session can serve it from. */
  saveImage: (dataUrl: string, prompt: string) => Promise<string>;
  /** Transcribes a stored audio attachment by id, caching the words on its row. */
  transcribeAttachment: (id: string) => Promise<string>;
  /** Uploads a stored PDF attachment to an MCP server and returns the server's upload id. */
  uploadAttachment: (server: McpServerRow, id: string) => Promise<string>;
  /**
   * Send an Ogg Opus voice note to this session's chat. Throws a reason the model can act
   * on when the channel cannot carry one.
   */
  sendVoiceNote: (bytes: Uint8Array) => Promise<string>;
  schedule: (when: string, prompt: string) => Promise<ScheduledTask>;
  listTasks: () => ScheduledTask[];
  cancelTask: (id: string) => Promise<boolean>;
};

export type ToolSpec = {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  run: (args: Record<string, unknown>, ctx: ToolContext) => Promise<string>;
};

const str = (v: unknown, fallback = "") => (typeof v === "string" ? v : fallback);

/** What the speaking model is told, so it reads the words instead of replying to them. */
const SPEAK_PROMPT =
  "You are a text-to-speech voice. Read the user's message aloud exactly as written, in its own language. Do not answer it, introduce it, or add a word of your own.";

/**
 * Collect a streamed spoken answer: base64 16-bit little-endian PCM chunks, complete only
 * at stream end. A mid-stream error is thrown so the model can explain the missing note.
 */
async function spokenSamples(res: Response): Promise<Int16Array> {
  const body = res.body;
  if (!body) throw new Error("the voice model sent no stream");
  const reader = body.getReader();
  const decoder = new TextDecoder();
  const chunks: Uint8Array[] = [];
  let buffered = "";
  let bytes = 0;
  for (;;) {
    const { done, value } = await reader.read();
    buffered += done ? "" : decoder.decode(value, { stream: true });
    // Only whole lines can be parsed; whatever follows the last newline is the start
    // of one and waits for the rest of it.
    const lines = buffered.split("\n");
    buffered = done ? "" : (lines.pop() ?? "");
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("data:")) continue;
      const payload = trimmed.slice(5).trim();
      if (payload === "" || payload === "[DONE]") continue;
      let event: {
        error?: { message?: string };
        choices?: { delta?: { audio?: { data?: string } } }[];
      };
      try {
        event = JSON.parse(payload);
      } catch {
        // OpenRouter sends keep-alive comments and the odd non-JSON line; neither is
        // audio and neither is a failure.
        continue;
      }
      if (event.error) throw new Error(event.error.message ?? "the voice model failed mid-stream");
      const data = event.choices?.[0]?.delta?.audio?.data;
      if (!data) continue;
      const decoded = base64Bytes(data);
      bytes += decoded.length;
      chunks.push(decoded);
    }
    if (done) break;
  }
  const pcm = new Uint8Array(bytes);
  let at = 0;
  for (const chunk of chunks) {
    pcm.set(chunk, at);
    at += chunk.length;
  }
  // An odd trailing byte is half a sample and belongs to nothing; `Int16Array` cannot
  // hold it either.
  return new Int16Array(pcm.buffer, 0, Math.floor(bytes / 2));
}

function base64Bytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** Rough HTML-to-text: enough for a model to read a page, cheap enough for a Worker. */
function htmlToText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

type SearchResult = { title: string; url: string; description?: string };

/** A self-hosted SearXNG instance. The fallback for agents with no Brave API key. Needs `formats: [json]` in its settings.yml. */
async function searxngSearch(
  base: string,
  token: string,
  query: string,
  count: number
): Promise<SearchResult[]> {
  if (!base) throw new Error("no Brave API key and no SearXNG URL is set");
  const url = `${base}/search?q=${encodeURIComponent(query)}&format=json`;
  const headers: Record<string, string> = { Accept: "application/json" };
  if (token) headers.Authorization = `Bearer ${token}`;
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`SearXNG returned ${res.status} ${await res.text()}`);
  const json = (await res.json()) as {
    results?: { title?: string; url?: string; content?: string }[];
  };
  return (json.results ?? [])
    .filter((r) => r.url)
    .slice(0, count)
    .map((r) => ({ title: r.title ?? r.url!, url: r.url!, description: r.content }));
}

/** Brave's hosted API. The default when a key is set. */
async function braveSearch(key: string, query: string, count: number): Promise<SearchResult[]> {
  const url = `https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}&count=${count}`;
  const res = await fetch(url, {
    headers: { Accept: "application/json", "X-Subscription-Token": key },
  });
  if (!res.ok) throw new Error(`Brave returned ${res.status} ${await res.text()}`);
  const json = (await res.json()) as { web?: { results?: SearchResult[] } };
  return json.web?.results ?? [];
}

export const TOOLS: ToolSpec[] = [
  {
    name: "web_search",
    description:
      "Search the web. Use for anything current, or any fact you are not certain of. Returns titles, URLs and snippets.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "The search query." },
        count: { type: "integer", description: "How many results, 1-10. Default 5." },
      },
      required: ["query"],
    },
    async run(args, ctx) {
      const query = str(args.query).trim();
      if (!query) throw new Error("query was empty");
      const count = Math.min(10, Math.max(1, Number(args.count) || 5));
      const brave = str(ctx.config.brave_api_key).trim();
      const results = brave
        ? await braveSearch(brave, query, count)
        : await searxngSearch(
            str(ctx.config.searxng_url).trim().replace(/\/+$/, ""),
            str(ctx.config.searxng_token).trim(),
            query,
            count
          );
      if (results.length === 0) return `No results for "${query}".`;
      return results
        .map((r, i) => `${i + 1}. ${r.title}\n${r.url}\n${htmlToText(r.description ?? "")}`)
        .join("\n\n");
    },
  },
  {
    name: "fetch_url",
    description:
      "Fetch a web page and return its readable text. Use after web_search when a snippet is not enough, or when the user pastes a link.",
    parameters: {
      type: "object",
      properties: { url: { type: "string", description: "An absolute http(s) URL." } },
      required: ["url"],
    },
    async run(args) {
      const raw = str(args.url).trim();
      let target: URL;
      try {
        target = new URL(raw);
      } catch {
        throw new Error(`"${raw}" is not a valid URL`);
      }
      if (target.protocol !== "http:" && target.protocol !== "https:") {
        throw new Error("only http and https URLs can be fetched");
      }
      const res = await fetch(target, {
        headers: { accept: "text/html,text/plain", "user-agent": "salts-agent/1.0" },
        redirect: "follow",
      });
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      const type = res.headers.get("content-type") ?? "";
      const body = await res.text();
      const text = type.includes("html") ? htmlToText(body) : body;
      // A tool result this long already dominates the prompt; more would just cost.
      return text.length > 12000 ? `${text.slice(0, 12000)}\n\n[truncated]` : text;
    },
  },
  {
    name: "generate_image",
    description:
      "Draw an image from a description and show it to the user. Returns Markdown that already renders in the chat, so repeat it in your reply rather than describing the image.",
    parameters: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "What to draw, in detail." },
      },
      required: ["prompt"],
    },
    async run(args, ctx) {
      const prompt = str(args.prompt).trim();
      if (!prompt) throw new Error("prompt was empty");
      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ctx.openrouterKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: ctx.config.image_model,
          modalities: ["image", "text"],
          messages: [{ role: "user", content: prompt }],
        }),
      });
      if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
      const json = (await res.json()) as {
        choices?: { message?: { images?: { image_url?: { url?: string } }[] } }[];
      };
      const dataUrl = json.choices?.[0]?.message?.images?.[0]?.image_url?.url;
      if (!dataUrl) return "Image generation returned no image. Try a different image model.";
      return `Image ready. Include exactly this in your reply: ![${prompt.slice(0, 60)}](${await ctx.saveImage(dataUrl, prompt)})`;
    },
  },
  {
    name: "transcribe_audio",
    description:
      "Transcribe an audio attachment the user sent. The message names each clip with its id. Call this when the words matter; the transcript is cached, so calling it twice on the same clip is free.",
    parameters: {
      type: "object",
      properties: {
        attachment_id: {
          type: "string",
          description: "The id of the audio attachment, as given in the message.",
        },
      },
      required: ["attachment_id"],
    },
    async run(args, ctx) {
      const id = str(args.attachment_id).trim();
      if (!id) throw new Error("attachment_id is required");
      const transcript = await ctx.transcribeAttachment(id);
      return transcript.trim() === "" ? "The clip transcribed to nothing." : transcript;
    },
  },
  {
    name: "send_voice_note",
    description:
      "Say something out loud and send it to the user as a voice note. Use it when they ask to be sent a voice note or voice message, or when hearing it beats reading it. The words are spoken and not shown, so write them the way you would say them, and keep your written reply as well.",
    parameters: {
      type: "object",
      properties: {
        text: {
          type: "string",
          description:
            "What to say, in the language the user is writing in. A few sentences: a voice note is listened to, not skimmed.",
        },
      },
      required: ["text"],
    },
    async run(args, ctx) {
      const text = str(args.text).trim();
      if (!text) throw new Error("text was empty");
      const spokenLimit = ctx.settings.voice_note_limit;
      if (text.length > spokenLimit) {
        throw new Error(
          `that is ${text.length} characters to say aloud; keep a voice note under ${spokenLimit}`
        );
      }
      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ctx.openrouterKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: ctx.config.voice_model,
          // OpenRouter's rules: audio output requires `stream`, and streams only offer `pcm16`,
          // which `pcm16ToOggOpus` packs into the Ogg Opus chat apps play.
          stream: true,
          modalities: ["text", "audio"],
          audio: { voice: "alloy", format: "pcm16" },
          // These models answer rather than read, so this keeps the note from being a reply to its text.
          messages: [
            { role: "system", content: SPEAK_PROMPT },
            { role: "user", content: text },
          ],
        }),
      });
      if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
      const pcm = await spokenSamples(res);
      if (pcm.length === 0)
        return "The voice model returned no audio. Try a different voice model.";
      return await ctx.sendVoiceNote(pcm16ToOggOpus(pcm, VOICE_SAMPLE_RATE));
    },
  },
  {
    name: "schedule_task",
    description:
      "Run a prompt later, once or repeatedly. The answer is posted into this session when it runs.",
    parameters: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "What to ask yourself when it runs." },
        when: {
          type: "string",
          description:
            "Either a delay in seconds ('900'), an ISO 8601 timestamp, or a 5-field cron expression ('0 9 * * *') for a repeating task.",
        },
      },
      required: ["prompt", "when"],
    },
    async run(args, ctx) {
      const prompt = str(args.prompt).trim();
      const when = str(args.when).trim();
      if (!prompt || !when) throw new Error("both prompt and when are required");
      const task = await ctx.schedule(when, prompt);
      return `Scheduled task ${task.id} for ${task.when}.`;
    },
  },
  {
    name: "list_scheduled_tasks",
    description: "List the tasks scheduled in this session.",
    parameters: { type: "object", properties: {} },
    async run(_args, ctx) {
      const tasks = ctx.listTasks();
      if (tasks.length === 0) return "No scheduled tasks.";
      return tasks.map((t) => `${t.id} — ${t.when} — ${t.prompt}`).join("\n");
    },
  },
  {
    name: "cancel_scheduled_task",
    description: "Cancel a scheduled task by its id.",
    parameters: {
      type: "object",
      properties: { id: { type: "string", description: "The task id." } },
      required: ["id"],
    },
    async run(args, ctx) {
      const id = str(args.id).trim();
      return (await ctx.cancelTask(id)) ? `Cancelled ${id}.` : `No task with id ${id}.`;
    },
  },
  {
    name: "remember",
    description:
      "Store a fact worth carrying into later sessions: a preference, a name, a decision. One fact per call, written so it still makes sense on its own.",
    parameters: {
      type: "object",
      properties: { text: { type: "string", description: "The fact, in one sentence." } },
      required: ["text"],
    },
    async run(args, ctx) {
      const text = str(args.text).trim();
      if (!text) throw new Error("nothing to remember");
      const memory = (await ctx.registry.remember(text.slice(0, 500), ctx.sessionId)) as Memory;
      return `Remembered (#${memory.id}): ${memory.text}`;
    },
  },
  {
    name: "recall",
    description:
      "Look up what you have remembered. Pass a word to search for, or leave the query empty for the most recent memories.",
    parameters: {
      type: "object",
      properties: { query: { type: "string", description: "A word or phrase to match." } },
    },
    async run(args, ctx) {
      const memories = (await ctx.registry.recall(str(args.query).trim(), 20)) as Memory[];
      if (memories.length === 0) return "Nothing remembered yet.";
      return memories.map((m) => `#${m.id} ${m.text}`).join("\n");
    },
  },
];

const TOOL_BY_NAME = new Map(TOOLS.map((t) => [t.name, t]));

/** The tools to offer this turn: those belonging to a ready capability. */
export function toolsFor(config: Config): ToolSpec[] {
  return CAPABILITIES.filter((c) => capabilityReady(c, config))
    .flatMap((c) => c.tools)
    .map((name) => TOOL_BY_NAME.get(name))
    .filter((t): t is ToolSpec => !!t);
}

/* ------------------------------------------------------------ mcp tools -- */

/**
 * A client for one server with credentials applied; an expiring OAuth token is
 * refreshed and written back so old connections keep working.
 */
export async function mcpClientFor(
  server: McpServerRow,
  registry: DurableObjectStub<SessionRegistry>
): Promise<McpClient> {
  const headers = server.auth === "headers" ? parseHeaders(server.headers) : {};
  if (server.auth !== "oauth") return new McpClient(server.url, headers);
  // The registry owns refreshing: it holds the row, and it is the only place that can
  // keep two of this server's tools from refreshing against each other.
  const fresh = await registry.refreshMcpToken(server.id);
  return new McpClient(server.url, headers, fresh?.oauth_access_token ?? "");
}

/**
 * Run against a server, retrying once with a fresh token on a 401: the stored expiry is
 * only a guess, and the provider's refusal is the authority.
 */
export async function withMcpAuth<T>(
  server: McpServerRow,
  registry: DurableObjectStub<SessionRegistry>,
  run: (client: McpClient) => Promise<T>
): Promise<T> {
  try {
    return await run(await mcpClientFor(server, registry));
  } catch (err) {
    if (!(err instanceof McpUnauthorized) || server.auth !== "oauth") throw err;
    const refreshed = await registry.refreshMcpToken(server.id, true);
    // A refresh that cleared the tokens already explained why in actionable words; prefer that.
    if (!refreshed?.oauth_access_token) {
      throw refreshed?.last_error ? new Error(refreshed.last_error) : err;
    }
    const retried = await run(new McpClient(refreshed.url, {}, refreshed.oauth_access_token));
    // The call works again, so whatever the card was reporting is out of date.
    if (server.last_error) await registry.noteMcpError(server.id, "");
    return retried;
  }
}

/** Whether a server is switched on and has whatever it needs to authenticate. */
export function mcpServerReady(server: McpServerRow): boolean {
  if (!server.enabled || !server.url.trim()) return false;
  if (server.auth === "oauth") return server.oauth_access_token !== "";
  return true;
}

/** How the model names an attachment in `upload_id`; swapped for the server's id on call. */
export const ATTACHMENT_REF = "attachment:";

/**
 * Whether a server takes uploads at `<base>/uploads`, inferred from a callable tool that
 * asks for an `upload_id`.
 */
export function acceptsUploads(server: McpServerRow): boolean {
  if (!mcpServerReady(server)) return false;
  const off = new Set(parseNames(server.disabled_tools));
  return parseTools(server.tools_json).some((tool) => {
    if (off.has(tool.name)) return false;
    const properties = tool.inputSchema?.properties;
    return typeof properties === "object" && properties !== null && "upload_id" in properties;
  });
}

/**
 * Every connected MCP server's tools as specs, schemas passed through, from the cached
 * `tools/list` so a turn adds no round trip.
 */
export function mcpToolSpecs(servers: McpServerRow[]): ToolSpec[] {
  const specs: ToolSpec[] = [];
  for (const server of servers) {
    if (!mcpServerReady(server)) continue;
    const off = new Set(parseNames(server.disabled_tools));
    for (const tool of parseTools(server.tools_json)) {
      // A tool switched off is never handed to the model, so it cannot be called.
      if (off.has(tool.name)) continue;
      specs.push({
        name: qualifiedName(server, tool.name),
        description: `[${server.name}] ${tool.description ?? tool.name}`,
        parameters: tool.inputSchema ?? { type: "object", properties: {} },
        async run(args, ctx) {
          try {
            // A file goes to a server only when the model hands it to one of its tools.
            const ref = typeof args.upload_id === "string" ? args.upload_id : "";
            if (ref.startsWith(ATTACHMENT_REF)) {
              const id = await ctx.uploadAttachment(server, ref.slice(ATTACHMENT_REF.length));
              args = { ...args, upload_id: id };
            }
            return await withMcpAuth(server, ctx.registry, (client) =>
              client.callTool(tool.name, args)
            );
          } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            // Without this the card would keep advertising a server whose every call
            // is failing, because only a tool sync ever wrote that field.
            await ctx.registry.noteMcpError(server.id, message);
            throw err;
          }
        },
      });
    }
  }
  return specs;
}

/** OpenRouter's `tools` array for those tools. */
export function toolDefinitions(config: Config) {
  return toolsFor(config).map((t) => ({
    type: "function" as const,
    function: { name: t.name, description: t.description, parameters: t.parameters },
  }));
}

/** Run one tool. Failures are returned, not thrown, so the model can correct itself. */
export async function runTool(
  name: string,
  args: Record<string, unknown>,
  ctx: ToolContext,
  /** The spec to run, for tools that live outside `TOOLS` — MCP's, for instance. */
  spec?: ToolSpec
): Promise<{ content: string; ok: boolean }> {
  const tool = spec ?? TOOL_BY_NAME.get(name);
  if (!tool) return { content: `Error: no tool named ${name}.`, ok: false };
  try {
    return { content: await tool.run(args, ctx), ok: true };
  } catch (err) {
    return {
      content: `Tool ${name} failed: ${err instanceof Error ? err.message : String(err)}`,
      ok: false,
    };
  }
}
